org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Fix for Windows Daemon compilation failed (File locking)
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.incremental.js=false
kotlin.incremental.multiplatform=false
org.gradle.caching=false
org.gradle.parallel=false
org.gradle.daemon=false
